### PR TITLE
Fix/help option command

### PR DESCRIPTION
**Pull request by SawaTszm**
@modocache 
Hi, first of all I'd like to thank you for the nice feature. This is a realization of what I was hoping to have.

I am very interested in modifying this to work in modern environments (Python 3.11, Django 4.1).
However, as this would be a very large migration, I have first modified the command to **only** work with the help option of the command.
Although it looks like a big change due to the formatter, all I did was fix a syntax that is not supported in the current version and fix the module import.

If you think this PR is an opportunity for good change, I'd like to try to continue maintaining it so that the actual commands work.
(If you find it difficult to keep up with checking maintenance, it would be great if you could let me know).

Sorry for the length, thanks for reading this far!

### CODE REVIEW

**Comment by modocache** [comment]
Hi @SawaTszm!

> If you find it difficult to keep up with checking maintenance, it would be great if you could let me know.

Yes, this is the case. I'd be happy to add you as an owner of this repository, so you'd be free to commit what you wish, and accept other pull requests. Or, if you'd prefer, you may fork this repository and work on your own, or create an entirely new repository of your own. What do you think?

**Comment by SawaTszm** [comment]
@modocache 
> I'd be happy to add you as an owner of this repository, so you'd be free to commit what you wish, and accept other pull requests. Or, if you'd prefer, you may fork this repository and work on your own, or create an entirely new repository of your own. What do you think?

Thanks for your reply! If it is a good option for you too, I will create my own new repository.
When I finish my work and publish it, is it OK to include a link to this repository as a one of reference in the README file etc.?

**Comment by modocache** [comment]
Sure, no problem! But you'll have to send me a pull request adding a link to your repository, and I'll merge it.

**Comment by SawaTszm** [comment]
I understand. Thank you for confirming this PR comment!
I will send you a PR to add link when it is completed.

I'll close this PR.

**Pull request closed without merging**
